image: decentraland/ci-node:latest

build:
  only:
    - release
  script:
    - npm install && npm run build
    - dcl-lock-sync
    - cd .ci && npm install && dcl-up website-add-mana
    - dcl-sync-release && cd ..
    - dcl-upload build
    - cd .ci && dcl-cache-invalidation
